name: findorigin
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/logo.jpg
    - images/HomePageImage.png
    - images/TikTok.png
    - images/Mitron.png
    - images/Play Store.png
    - images/WhatsApp.jpeg
    - images/telegram.jpg
    - images/wechat.jpg
    - images/hike.png
    - images/indian messenger.png
    - images/pubg.jpg
    - images/fortnite.webp
    - images/u dictionary.webp
    - images/english hindi dictionary.webp
    - images/wps.webp
    - images/microsoft_office.webp
    - images/officeSuite.webp
    - images/libre_office.webp
    - images/gogle_docs.webp
    - images/zoom.webp
    - images/google_meet.webp
    - images/say_namaste.webp
    - images/jio_meet.webp
    - images/skype.webp
    - images/picsart.webp
    - images/beautyplus.webp
    - images/photoeditorpro.webp
    - images/toolwhiz.webp
    - images/camscanner.webp
    - images/zohoscanner.webp
    - images/dubsmaash.webp
    - images/likee.webp
    - images/vigovideo.webp
    - images/helo.webp
    - images/roposo.webp
    - images/boloindya.webp
    - images/adobescan.webp
    - images/microsoftofficelens.webp
    - images/docscan.webp
    - images/ucbrowser.webp
    - images/firefox.webp
    - images/brave.webp
    - images/goog;e chrome.webp
    - images/jiobrowser.webp
    - images/epicbrowser.webp
    - images/indianbrowser.webp
    - images/indbrowser.webp
    - images/apusbrowser.webp
    - images/applock.webp
    - images/vault.webp
    - images/norton.webp
    - images/applockfinger.webp
    - images/udictionary.webp
    - images/romwe.webp
    - images/shein.webp
    - images/aliexpress.webp
    - images/clubfact.webp
    - images/alibaba.webp
    - images/tatacliq.webp
    - images/ajio.webp
    - images/flipkart.webp
    - images/limeroad.webp
    - images/myntra.webp
    - images/snapdeal.webp
    - images/indiamart.webp
    - images/reldigital.webp
    - images/paytmmall.webp
    - images/shopclues.webp
    - images/ebay.webp
    - images/amazon.webp
    - images/vivavideo.webp
    - images/photovideo.webp
    - images/inshot.webp
    - images/kinemaster.webp
    - images/newsdog.webp
    - images/ucnews.webp
    - images/inshorts.webp
    - images/dailyhunt.webp
    - images/ET.webp
    - images/mint.webp
    - images/hindu.webp
    - images/TOI.webp
    - images/ndtv.webp
    - images/indiaexp.webp
    - images/dainikbhaskr.webp
    - images/bbcnews.webp
    - images/guardian.webp
    - images/TWP.webp
    - images/NYT.webp
    - images/cnn.webp
    - images/CNBC.webp
    - images/superbeam.webp
    - images/shareme.webp
    - images/shareit.webp
    - images/zapya.webp
    - images/xender.webp
    - images/jioswitch.webp
    - images/shareall.webp
    - images/sendany.webp
    - images/filegoogle.webp
    - images/adv_screen_recorder.webp
    - images/screencam_screenrecorder.webp
    - images/az_screenrecorder.webp
    - images/screen_recorder_no_ads.webp
    - images/SelfieCity.webp
    - images/mix_camera_360.webp
    - images/retrica.webp
    - images/indian selfie camera.webp
    - images/facetune2.webp
    - images/makeup_plus.webp
    - images/alipay.webp
    - images/paytm.webp
    - images/phone_pe.webp
    - images/google_pay.webp
    - images/nonolive.webp
    - images/houseparty.webp
    - images/twitch.webp
    - images/livestream.webp
    - images/loco.webp
    - images/nimo.webp
    - images/parallel_space.webp
    - images/app_cloner.webp
    - images/clone_app.webp
    - images/turbo_vpn.webp
    - images/proton_vpn.webp
    - images/empire_and_allies.webp
    - images/clash_royale.webp
    - images/clash_of_clans.webp
    - images/mobile_legends.webp
    - images/Vainglory.webp
    - images/arena_of_valor.webp
    - images/apps.jpg
    - images/gaana.webp
    - images/spotify.webp
    - images/saavn.webp
    - images/wynk.webp
    - images/amazon_music.webp
    - images/hungama.webp
    - images/google_play_music.webp


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
